# Generated by Django 4.0.3 on 2022-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocr',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
