# Generated by Django 4.0.3 on 2022-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textocr', '0002_ocr_content_ocr_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocr',
            name='content',
        ),
        migrations.AlterField(
            model_name='ocr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
